# load our environment
require_relative './config/environment'
# make the rake tasks in the sinatra-activerecord gem available
require 'sinatra/activerecord/rake'

desc 'Launch Pry console'
task :console do
  Pry.start
end
