source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', '~> 4.2'
gem 'sqlite3'
gem 'rspec-rails'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'capybara'
  gem 'pry'
	gem 'byebug'
end

group :development do
end
