# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem 'rspec'
gem 'pry'
gem 'shotgun'
gem 'require_all'
gem 'sqlite3'
gem 'sinatra-activerecord'


group :test, :development do
  gem 'rspec'
  gem 'capybara'
  gem 'pry'
end
